---
# Main tasks for setting up the HTTP server using Podman
- name: Pull the HTTP server image (Apache)
  ansible.builtin.command: podman pull docker.io/library/httpd:latest
  tags: http

- name: Create a directory for HTTP server files
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: '0755'
  tags: http

- name: Copy the test HTML page to the HTTP server directory
  ansible.builtin.template:
    src: templates/test_page.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  tags: http

- name: Run the HTTP server container with Podman
  containers.podman.podman_container:
    name: httpd_server
    image: docker.io/library/httpd:latest
    state: started
    ports:
      - "{{ http_port }}:80"
    volumes:
      - /var/www/html:/usr/local/apache2/htdocs:Z
    restart_policy: unless-stopped
  tags: http
