# Use the official Debian 13 (Trixie) base image
FROM debian:trixie

# Set environment variables (optional)
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt install -y \
    wget && \
    wget https://enterprise.proxmox.com/debian/proxmox-archive-keyring-trixie.gpg -O /usr/share/keyrings/proxmox-archive-keyring.gpg

RUN printf 'Types: deb\nURIs: http://download.proxmox.com/debian/pve\nSuites: trixie\nComponents: pve-no-subscription\nSigned-By: /usr/share/keyrings/proxmox-archive-keyring.gpg\n' > /etc/apt/sources.list.d/pve-install-repo.sources

RUN apt update && \
    apt install -y \
    proxmox-auto-install-assistant && \
    rm -rf /var/lib/apt/lists/*