---
- name: Install Podman
  ansible.builtin.dnf:
    name: podman
    state: present
  tags: podman

- name: Verify Podman Installation
  ansible.builtin.command: podman --version
  register: podman_version_output
  changed_when: false
  tags: podman

- name: Display Podman Version
  ansible.builtin.debug:
    msg: "Podman version installed: {{ podman_version_output.stdout }}"
  tags: podman
